[package]
authors = ["dawid@bautsch.pl"]
name = "rust_helloworld"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/dbautsch/rust_helloworld"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
